Added metadata_autotag and backup_database
stg-annon/stashapi pull request #11
Opened 2024-08-08 10:37 UTC by David-Maisonave

metadata_autotag has same interface as metadata_clean.
backup_database takes no arguments.

2024-08-10 17:29 UTC, stg-annon requested changes
thanks for the contribution but this should probably be a separate PR from 
> "Added metadata_autotag and backup_database"

2024-08-10 17:29 UTC, stg-annon commented on stashapp.py
> +	def metadata_autotag(self, paths:list=[], dry_run=False):
we would either want to accept all possible values for `AutoTagMetadataInput` or just accept a dict so the user can pass the whole input themselves

2024-08-11 14:19 UTC, David-Maisonave commented on stashapp.py
> +	def metadata_autotag(self, paths:list=[], dry_run=False):
> we would either want to accept all possible values for AutoTagMetadataInput or just accept a dict so the user can pass the whole input themselves

How would that be implemented?

> thanks for the contribution but this should probably be a separate PR from

I agree.  I didn't meant for the template  changes to get bunch together with these changes.  I'll pull the template changes out, and wait until this goes through.

2024-08-11 20:56 UTC, stg-annon commented on stashapp.py
> +	def metadata_autotag(self, paths:list=[], dry_run=False):
for example
```py
def metadata_autotag(self, paths:list=[], performers:list=[], stuios:list=[], tags:list=[]):
	metadata_autotag_input = {
		"paths":paths,
		"performers": performers,
		"studios":studios
		"tags":tags
	}
```
or 

```py
def metadata_autotag(self, input:dict={}):
	metadata_autotag_input = input
```
you can see the documentation for the api in the `/playground` in your stash
![image](https://github.com/user-attachments/assets/6a3ff599-38b3-490c-9f90-8073f203cf8f)



also just noticing the `dry_run` flag is not needed here

2024-08-12 20:44 UTC, David-Maisonave commented
> also just noticing the dry_run flag is not needed here

Yes, this gave me problems when I was trying to implemented, because I tried to duplicate the code I saw in metadata_clean. It kept failing until I realized I had to remove **dry_run** from metadata_autotag_input.
I guess I forgot to remove it from the input arguments.

I'll update changes shortly.

2024-08-12 20:59 UTC, David-Maisonave commented
I'm removing the check for paths being empty, since it works even if it's empty.
```
            if not paths:
                return
```

Why is this check in **metadata_clean**? When I remove it from that function, it also works with no input.
Do you have any issues with me removing it from both **metadata_autotag** and **metadata_clean** on this update?

2024-08-12 21:29 UTC, David-Maisonave commented
> you can see the documentation for the api in the /playground in your stash

I guess I'm must be missing something obvious here, because I don't see how you got that screen display.
I did try populating the GraphiQL with the following, but got an error:
```
{
		mutation MetadataAutoTag($input:AutoTagMetadataInput!) {
		    metadataAutoTag(input: $input)
		}
}
```

How did you get that screen?

2024-08-12 22:02 UTC, David-Maisonave commented
I figured out how to use the playground, and I now know what you mean my self documenting. But that doc button is tiny and it's in the upper right corner where it's easy to miss.

I recommend putting some screen shots in the ReadMe for [CommunityScripts ](https://github.com/stashapp/CommunityScripts) showing how to access the document.
Example Usage Instructions:
- Enter http://localhost:9999/playground on your browser, and click on the document button on the right side of the screen.
- ![GraphiQL_Doc1](https://github.com/user-attachments/assets/6e852fc2-2477-4ea2-9000-be742a19bf4e)
- Click on the interested sub section ([Query](http://localhost:9999/playground#), [Mutation](http://localhost:9999/playground#), or [Subscription](http://localhost:9999/playground#))
- ![GraphiQL_Doc2](https://github.com/user-attachments/assets/01ca52b7-51a3-4ba9-b7c3-dc6a0e42fc30)
- That will display a list of documented API's.
- ![GraphiQL_Doc3](https://github.com/user-attachments/assets/4d7a05f7-dbdd-4099-89a1-1f46f3648d5d)
- Clicking on the input variables will display more details.

2024-08-14 09:17 UTC, David-Maisonave commented
Added metadata_clean_generated.

I believe I made all the changes per review.
Please let me know if I missed anything.

2024-08-28 07:49 UTC, David-Maisonave commented
Please let me know if there's no interest in this pull request so I can close it.

Thank you

2024-08-28 16:22 UTC, stg-annon approved these changes

2024-08-28 16:22 UTC, merged